name: Build FFmpeg for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [arm64-v8a]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Android NDK
        uses: actions/setup-android-ndk@v3
        with:
          ndk-version: 'r26d'  # Eng so‘nggi NDK versiyasidan foydalanamiz
          local-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git

      - name: Clone FFmpeg repository
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          git checkout n6.0  # So‘nggi stabil versiyani tanlaymiz

      - name: Build FFmpeg
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_ROOT }}
        run: |
          cd ffmpeg

          # Umumiy minimal API darajasini belgilash
          API_LEVEL=21

          # Arxitekturaga qarab o‘zgaruvchilarni belgilash
          case ${{ matrix.arch }} in
            "arm64-v8a")
              CPU=armv8-a
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${API_LEVEL}-clang
              NM=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-nm
              EXTRA_CFLAGS="-march=armv8-a -fPIC -D__ANDROID_API__=${API_LEVEL}"
              ;;
          esac

          # FFmpeg-ni konfiguratsiya qilish
          ./configure \
            --target-os=android \
            --arch=${{ matrix.arch }} \
            --cpu=$CPU \
            --enable-cross-compile \
            --cross-prefix=$CROSS_PREFIX \
            --nm=$NM \
            --cc=$CC \
            --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
            --extra-cflags="$EXTRA_CFLAGS" \
            --extra-ldflags="-Wl,--no-undefined" \
            --prefix=../output/${{ matrix.arch }}/lib \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --disable-everything \
            --enable-avcodec \
            --enable-avformat \
            --enable-avutil \
            --enable-swscale \
            --enable-swresample \
            --enable-decoder=h264 \
            --enable-decoder=mp3 \
            --enable-demuxer=mpegts \
            --enable-demuxer=mp3 \
            --enable-muxer=mp4 \
            --enable-neon \
            --disable-asm  # Assembler optimallashtirishni o‘chirish (vaqtinchalik)

          # Xatolikni tekshirish
          if [ $? -ne 0 ]; then
            echo "Konfiguratsiya xatosi yuz berdi"
            cat config.log
            exit 1
          fi

          # Kompilyatsiya va o‘rnatish
          make -j$(nproc)
          mkdir -p ../output/${{ matrix.arch }}/lib
          make install
          if [ $? -ne 0 ]; then
            echo "O‘rnatish xatosi yuz berdi"
            cat config.log
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ matrix.arch }}
          path: output/${{ matrix.arch }}/lib/
