name: Android uchun FFmpeg-ni kompilyatsiya qilish

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armeabi-v7a, arm64-v8a, x86, x86_64]
    timeout-minutes: 600
    steps:
      - name: Repozitoriyani yuklab olish
        uses: actions/checkout@v3

      - name: Kerakli paketlarni o‘rnatish
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm libx264-dev libmp3lame-dev texi2html libxml2-utils

      - name: Android NDK-ni yuklab olish
        run: |
          NDK_VERSION="r25b"
          NDK_ZIP="android-ndk-${NDK_VERSION}-linux.zip"
          wget https://dl.google.com/android/repository/${NDK_ZIP}
          unzip ${NDK_ZIP} -d ~/
          export ANDROID_NDK_HOME=~/android-ndk-${NDK_VERSION}
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV

      - name: NDK o‘rnatilganligini tekshirish
        run: |
          if [ -d "$ANDROID_NDK_HOME" ]; then
            echo "NDK muvaffaqiyatli o‘rnatildi: $ANDROID_NDK_HOME"
          else
            echo "NDK o‘rnatishda xatolik yuz berdi!"
            exit 1
          fi

      - name: FFmpeg-ni kompilyatsiya qilish
        run: |
          # Umumiy minimal API darajasini belgilash
          API_LEVEL=21

          # Arxitekturaga qarab o‘zgaruvchilarni belgilash
          case ${{ matrix.arch }} in
            "armeabi-v7a")
              CPU=armv7-a
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi${API_LEVEL}-clang
              NM=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi-nm
              EXTRA_CFLAGS="-march=armv7-a -mfpu=neon -mfloat-abi=softfp -fPIC -D__ANDROID_API__=${API_LEVEL}"
              ;;
            "arm64-v8a")
              CPU=armv8-a
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${API_LEVEL}-clang
              NM=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-nm
              EXTRA_CFLAGS="-march=armv8-a -fPIC -D__ANDROID_API__=${API_LEVEL}"
              ;;
            "x86")
              CPU=i686
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android${API_LEVEL}-clang
              NM=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-nm
              EXTRA_CFLAGS="-march=i686 -fPIC -D__ANDROID_API__=${API_LEVEL}"
              ;;
            "x86_64")
              CPU=x86_64
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android${API_LEVEL}-clang
              NM=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-nm
              EXTRA_CFLAGS="-march=x86-64 -fPIC -D__ANDROID_API__=${API_LEVEL}"
              ;;
          esac

          # FFmpeg-ni konfiguratsiya qilish
          ./configure \
            --target-os=android \
            --arch=${{ matrix.arch }} \
            --cpu=$CPU \
            --enable-cross-compile \
            --cross-prefix=$CROSS_PREFIX \
            --nm=$NM \
            --cc=$CC \
            --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
            --extra-cflags="$EXTRA_CFLAGS" \
            --extra-ldflags="-Wl,--no-undefined" \
            --prefix=../output/${{ matrix.arch }}/lib \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --disable-everything \
            --enable-avcodec \
            --enable-avformat \
            --enable-avutil \
            --enable-swscale \
            --enable-swresample \
            --enable-decoder=h264 \
            --enable-decoder=mp3 \
            --enable-demuxer=mpegts \
            --enable-demuxer=mp3 \
            --enable-muxer=mp4 \
            --enable-neon

          # Xatolikni tekshirish
          if [ $? -ne 0 ]; then
            echo "Konfiguratsiya xatosi yuz berdi"
            cat config.log
            exit 1
          fi

          # Kompilyatsiya va o‘rnatish
          make -j$(nproc)
          mkdir -p ../output/${{ matrix.arch }}/lib
          make install
          if [ $? -ne 0 ]; then
            echo "O‘rnatish xatosi yuz berdi"
            cat config.log
            exit 1
          fi

      - name: Natijalarni yuklash
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ matrix.arch }}
          path: ../output/${{ matrix.arch }}/lib/
