name: Build FFmpeg for Android

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armeabi-v7a, arm64-v8a, x86, x86_64]
    timeout-minutes: 60  # Vaqt chegarasini oshirish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm libx264-dev libmp3lame-dev texi2html xmllint

      - name: Download NDK from official source
        run: |
          NDK_VERSION="r25b"
          NDK_ZIP="android-ndk-${NDK_VERSION}-linux.zip"
          wget https://dl.google.com/android/repository/${NDK_ZIP}
          unzip ${NDK_ZIP} -d ~/
          export ANDROID_NDK_HOME=~/android-ndk-${NDK_VERSION}
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV

      - name: Verify NDK setup
        run: |
          if [ -d "$ANDROID_NDK_HOME" ]; then
            echo "NDK setup successful at $ANDROID_NDK_HOME"
          else
            echo "NDK setup failed!"
            exit 1
          fi

      - name: Build FFmpeg
        run: |
          case ${{ matrix.arch }} in
            "armeabi-v7a")
              CPU=armv7-a
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang
              ;;
            "arm64-v8a")
              CPU=armv8-a
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android23-clang
              ;;
            "x86")
              CPU=i686
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang
              ;;
            "x86_64")
              CPU=x86_64
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android23-clang
              ;;
          esac

          ./configure \
            --target-os=android \
            --arch=${{ matrix.arch }} \
            --cpu=$CPU \
            --enable-cross-compile \
            --cross-prefix=$CROSS_PREFIX \
            --cc=$CC \
            --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
            --extra-cflags="-march=$CPU -fPIC -D__ANDROID_API__=23" \
            --prefix=../output/${{ matrix.arch }} \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --disable-everything \
            --enable-avcodec \
            --enable-avformat \
            --enable-avutil \
            --enable-swscale \
            --enable-swresample \
            --enable-decoder=h264 \
            --enable-decoder=mp3 \
            --enable-demuxer=mp4 \
            --enable-demuxer=mp3 || { echo "Configure failed"; cat config.log; exit 1; }

          make -j1
          mkdir -p ../output/${{ matrix.arch }}/lib
          make install || { echo "Make install failed"; cat config.log; exit 1; }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ matrix.arch }}
          path: ../output/${{ matrix.arch }}/lib/
