name: Build FFmpeg for Android
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armeabi-v7a, arm64-v8a, x86, x86_64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache NDK
        uses: actions/cache@v3
        with:
          path: ~/android-ndk
          key: ndk-r26b-${{ runner.os }}
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
          add-to-path: true
          link-to-sdk: false
          local-cache: true
      - name: Build FFmpeg
        run: |
          cd ffmpeg
          echo "Building for ${{ matrix.arch }}"
          case ${{ matrix.arch }} in
            "armeabi-v7a")
              CPU=armv7-a
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang
              ;;
            "arm64-v8a")
              CPU=armv8-a
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
              ;;
            "x86")
              CPU=i686
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang
              ;;
            "x86_64")
              CPU=x86_64
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang
              ;;
          esac
          if [ ! -f configure ]; then
            echo "configure file not found in ffmpeg directory!"
            exit 1
          fi
          ./configure \
            --target-os=android \
            --arch=${{ matrix.arch }} \
            --cpu=$CPU \
            --enable-cross-compile \
            --cross-prefix=$CROSS_PREFIX \
            --cc=$CC \
            --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
            --extra-cflags="-march=$CPU -fPIC -D__ANDROID_API__=21" \
            --prefix=../output/${{ matrix.arch }} \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --disable-everything \
            --enable-avcodec \
            --enable-avformat \
            --enable-avutil \
            --enable-swscale \
            --enable-swresample \
            --enable-decoder=h264 \
            --enable-decoder=mp3 \
            --enable-demuxer=mp4 \
            --enable-demuxer=mp3 || { echo "Configure failed"; exit 1; }
          make -j1
          mkdir -p ../output/${{ matrix.arch }}/lib
          make install || { echo "Make install failed"; exit 1; }
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ matrix.arch }}
          path: output/${{ matrix.arch}}/lib/
