name: Build FFmpeg for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [arm64-v8a, x86_64]  # arm64-v8a va x86_64 arxitekturalari

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: '28.0.13004108'  # NDK 28.0.13004108 versiyasi
          add-to-path: true

      - name: Fallback to manual NDK download if needed
        if: failure()  # Agar NDK yuklanmasa, qo‘lda yuklash
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r28-linux.zip
          unzip android-ndk-r28-linux.zip -d ./ndk
          echo "ANDROID_NDK_HOME=$(pwd)/ndk/android-ndk-r28" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git

      - name: Clone FFmpeg repository
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          git checkout n6.0  # FFmpegning so‘nggi stabil versiyasi (2025-yil mart)

      - name: Build FFmpeg for ${{ matrix.arch }}
        env:
          ANDROID_NDK_HOME: ${{ env.NDK_ROOT }}
        run: |
          cd ffmpeg

          # API darajasini Android 15 (API 35) ga moslashtirish
          API_LEVEL=35

          # Arxitekturaga qarab o‘zgaruvchilarni belgilash
          case ${{ matrix.arch }} in
            "arm64-v8a")
              ARCH=arm64-v8a
              CPU=armv8-a
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${API_LEVEL}-clang
              NM=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-nm
              EXTRA_CFLAGS="-march=armv8-a -fPIC -D__ANDROID_API__=${API_LEVEL} -O3"
              ;;
            "x86_64")
              ARCH=x86_64
              CPU=x86-64
              CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-
              CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android${API_LEVEL}-clang
              NM=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-nm
              EXTRA_CFLAGS="-march=x86-64 -fPIC -D__ANDROID_API__=${API_LEVEL} -O3"
              ;;
          esac

          EXTRA_LDFLAGS="-Wl,--no-undefined"

          # FFmpeg-ni konfiguratsiya qilish
          ./configure \
            --target-os=android \
            --arch=$ARCH \
            --cpu=$CPU \
            --enable-cross-compile \
            --cross-prefix=$CROSS_PREFIX \
            --nm=$NM \
            --cc=$CC \
            --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
            --extra-cflags="$EXTRA_CFLAGS" \
            --extra-ldflags="$EXTRA_LDFLAGS" \
            --prefix=../output/$ARCH/lib \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-programs \
           
