name: Build FFmpeg for Android (arm64-v8a)

on:
  push:
    branches:
      - main  # Yoki master
  pull_request:
    branches:
      - main  # Yoki master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repozitoriyani yuklab olish
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Android NDK ni sozlash
      - name: Set up Android NDK
        uses: android-actions/setup-android-ndk@v1
        with:
          version: 25.1.8937393  # Mavjud NDK versiyasini ko'rsating
          add-to-path: true      # NDK ni PATH ga qo'shish
          local-cache: true      # NDK ni lokal keshlash

      # 3. FFmpeg ni qurish uchun kerakli paketlarni o'rnatish
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            nasm \
            git \
            curl

      # 4. FFmpeg ni klonlash va sozlash
      - name: Clone and configure FFmpeg
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          ./configure \
            --enable-shared \
            --disable-static \
            --arch=arm64 \
            --target-os=android \
            --enable-cross-compile \
            --cross-prefix=aarch64-linux-android- \
            --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
            --prefix=./output

      # 5. FFmpeg ni qurish
      - name: Build FFmpeg
        run: |
          cd ffmpeg
          make -j$(nproc)
          make install

      # 6. Qurilgan fayllarni saqlash (artifact sifatida)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-build
          path: ffmpeg/output
