name: FFmpeg Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build FFmpeg (arm64-v8a & x86_64)
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Repozitoriyani yuklash
        uses: actions/checkout@v4
        with:
          repository: TINCHLIK/ffmpeg-android-build
          fetch-depth: 1

      - name: NDK keshini tekshirish
        id: cache-ndk
        uses: actions/cache@v3
        with:
          path: ./ndk
          key: ndk-r28-${{ runner.os }}

      - name: Android NDKni o‘rnatish
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          echo "NDK yuklash boshlandi"
          wget https://dl.google.com/android/repository/android-ndk-r28-linux.zip
          echo "Yuklash tugadi, chiqarish boshlanadi"
          unzip android-ndk-r28-linux.zip -d ./ndk
          echo "Chiqarish tugadi"
          echo "ANDROID_NDK_HOME=$(pwd)/ndk/android-ndk-r28" >> $GITHUB_ENV

      - name: NDK muhitini tekshirish
        run: |
          echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
          ls -la $ANDROID_NDK_HOME

      - name: FFmpegni qurish (arm64-v8a)
        run: |
          echo "arm64-v8a qurish boshlandi"
          ./build_script.sh arm64-v8a
          echo "arm64-v8a qurildi"

      - name: FFmpegni qurish (x86_64)
        run: |
          echo "x86_64 qurish boshlandi"
          ./build_script.sh x86_64
          echo "x86_64 qurildi"

      - name: Qurilishdan keyin natijalarni tekshirish
        run: |
          echo "Barcha natija fayllari:"
          find . -name "*.so" || echo "Hech qanday .so fayl topilmadi"

      - name: Qurilishdan so‘ng `.so` fayllarni yuklab olish
        uses: actions/upload-artifact@v3
        with:
          name: FFmpeg-libraries
          path: |
            **/*.so
