name: FFmpeg Android Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build FFmpeg for Android
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        arch: [arm64-v8a, x86_64] # Ikkita arxitektura uchun ishlaydi

    steps:
      # 1️⃣ Repozitoriyani yuklash
      - name: Repozitoriyani yuklash
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2️⃣ NDK keshini tekshirish
      - name: NDK keshini tekshirish
        id: cache-ndk
        uses: actions/cache@v3
        with:
          path: ./ndk
          key: ndk-r28-${{ runner.os }}

      # 3️⃣ NDK yuklash (agar keshta bo‘lmasa)
      - name: Android NDKni o‘rnatish
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          echo "NDK yuklash boshlandi"
          wget https://dl.google.com/android/repository/android-ndk-r28-linux.zip
          echo "Yuklash tugadi, chiqarish boshlanadi"
          unzip android-ndk-r28-linux.zip -d ./ndk
          echo "Chiqarish tugadi"
          echo "ANDROID_NDK_HOME=$(pwd)/ndk/android-ndk-r28" >> $GITHUB_ENV

      # 4️⃣ NDK muhitini tasdiqlash
      - name: NDK muhitini tekshirish
        run: |
          echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
          ls -la $ANDROID_NDK_HOME

      # 5️⃣ FFmpeg qurish
      - name: FFmpegni qurish (${{ matrix.arch }})
        run: |
          echo "Qurish jarayoni boshlandi (${matrix.arch})"
          chmod +x build_ffmpeg.sh
          ./build_ffmpeg.sh ${{ matrix.arch }}

      # 6️⃣ .so fayllarni yuklash
      - name: Kutubxonalarni yuklash
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-libs-${{ matrix.arch }}
          path: |
            **/*.so
