name: Build FFmpeg for Android

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86, x86_64]
    steps:
      - name: Repozitoriyani yuklash
        uses: actions/checkout@v3

      - name: NDK keshi tekshirish
        id: ndk-cache
        uses: actions/cache@v3
        with:
          path: ~/android-ndk-r25c
          key: ndk-r25c

      - name: Android NDK'ni o‘rnatish
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip -d ~/
          rm android-ndk-r25c-linux.zip

      - name: NDK muhitini tekshirish
        run: echo "NDK o‘rnatildi va yo‘nalish sozlandi."

      - name: FFmpegni qurish (${{ matrix.arch }})
        run: |
          echo "Qurish jarayoni boshlandi (${{ matrix.arch }})"
          # Bu yerga qurish jarayoni uchun kerakli buyruqlarni qo‘shing
          mkdir -p output/${{ matrix.arch }}
          echo "Bu test fayl" > output/${{ matrix.arch }}/test.txt

      - name: Kutubxonalarni yuklash
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-${{ matrix.arch }}
          path: output/${{ matrix.arch }}/*
