name: Build FFmpeg for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86, x86_64]
    
    steps:
      - name: Repozitoriyani yuklash
        uses: actions/checkout@v4

      - name: NDK keshini tekshirish
        id: ndk-cache
        uses: actions/cache@v3
        with:
          path: ~/android-ndk
          key: ndk-${{ runner.os }}-${{ matrix.arch }}

      - name: Android NDKni o‘rnatish
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip -d ~/
          mv ~/android-ndk-r25b ~/android-ndk

      - name: NDK muhitini tekshirish
        run: echo "NDK o‘rnatildi:" ${{ matrix.arch }}

      - name: FFmpegni qurish (${{ matrix.arch }})
        run: echo "Qurish jarayoni boshlandi (${{ matrix.arch }})"

      - name: Kutubxonalarni yuklash
        run: |
          echo "FFmpeg uchun kerakli kutubxonalar yuklanmoqda..."

      - name: Post NDK keshini tekshirish
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: echo "NDK keshi yangilandi"

      - name: Post Repozitoriyani yuklash
        run: echo "Repo yuklandi, jarayon yakunlandi."

