name: Build FFmpeg for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: '25.1.8937393'  # Sizning NDK versiyangiz
          add-to-path: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git

      - name: Clone FFmpeg repository
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          git checkout n6.0  # FFmpegning so‘nggi stabil versiyasi (2025-yil mart holatiga)

      - name: Build FFmpeg for arm64-v8a
        env:
          ANDROID_NDK_HOME: ${{ env.NDK_ROOT }}
        run: |
          cd ffmpeg

          # API darajasini Android 15 (API 35) ga moslashtirish
          API_LEVEL=35

          # Arxitektura o‘zgaruvchilari (faqat arm64-v8a)
          ARCH=arm64-v8a
          CPU=armv8-a
          CROSS_PREFIX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-
          CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${API_LEVEL}-clang
          NM=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-nm
          EXTRA_CFLAGS="-march=armv8-a -fPIC -D__ANDROID_API__=${API_LEVEL} -O3"
          EXTRA_LDFLAGS="-Wl,--no-undefined"

          # FFmpeg-ni konfiguratsiya qilish
          ./configure \
            --target-os=android \
            --arch=$ARCH \
            --cpu=$CPU \
            --enable-cross-compile \
            --cross-prefix=$CROSS_PREFIX \
            --nm=$NM \
            --cc=$CC \
            --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
            --extra-cflags="$EXTRA_CFLAGS" \
            --extra-ldflags="$EXTRA_LDFLAGS" \
            --prefix=../output/$ARCH/lib \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --disable-everything \
            --enable-avcodec \
            --enable-avformat \
            --enable-avutil \
            --enable-swscale \
            --enable-swresample \
            --enable-decoder=h264 \
            --enable-decoder=mp3 \
            --enable-demuxer=mpegts \
            --enable-demuxer=mp3 \
            --enable-muxer=mp4 \
            --enable-neon \
            --enable-small  # Kichikroq hajm uchun optimallashtirish

          # Konfiguratsiya xatoliklarini tekshirish
          if [ $? -ne 0 ]; then
            echo "Konfiguratsiya xatosi yuz berdi"
            cat config.log
            exit 1
          fi

          # Kompilyatsiya va o‘rnatish
          make -j$(nproc)
          mkdir -p ../output/$ARCH/lib
          make install
          if [ $? -ne 0 ]; then
            echo "Kompilyatsiya yoki o‘rnatish xatosi yuz berdi"
            cat config.log
            exit 1
          fi

      - name: Upload FFmpeg .so files
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-arm64-v8a
          path: output/arm64-v8a/lib/*.so

      - name: Verify generated .so files
        run: |
          echo "Yaratilgan .so fayllarni tekshirish:"
          ls -lh output/arm64-v8a/lib/*.so
